### PR TITLE
Update code to reflect NewEgg UI as of 12/24/20

### PR DESCRIPTION
**Pull request by wcedmisten**
Should fix https://github.com/Ataraksia/NeweggBot/issues/32

I pulled in only the minimal *necessary* changes from https://github.com/Codolophier/NeweggBot, and not the refactoring changes. It seems like that refactoring is a good idea, but this PR should serve to get the repo working on NewEgg in its current state, with less review overhead.

I also added code to close the popup suggesting the user to buy a KN 95 mask, that appears when adding an item to the cart.

### CODE REVIEW

**Comment by wcedmisten** [comment]
> Tried this neweggbot.js but it makes the firefox nightly start in the background with no window pop up and no way to bring it to the forefront. I can only see it running in the processes. The master neweggbot.js worked fine though but I would like to ensure the "N95 mask" pop up is taken care of and therefore wanted to use this modified .js file.

Hmm, this code shouldn't change how the browser is launched, so I'm not sure why this happens, but I'll add a line to make sure it doesn't launch in headless mode. Until then, you can try adding 

headless: false 

To the launch() parameters

**Comment by wcedmisten** [comment]
@batrarobin I committed a change to force disable headless mode for the browser, so that should fix the issue.

**Comment by quantumvenom** [comment]
This worked for me with a VPN off, but as soon as I turn on VPN it returns to adding more items to cart and not checking out, could it be the added delay with the VPN?

**Comment by wcedmisten** [comment]
@quantumvenom could you describe the functionality for combos you mention? I'm not quite sure what you mean by that, or if that functionality exists in the base repo.

It would also be helpful if you could provide logs for the cart looping issue.

Thanks!

**Comment by quantumvenom** [comment]
@wcedmisten how would I export a log from the script exactly? And for combos I mean the combo URL that takes the place of the item #, for example, "Combo.4212336".

**Comment by wcedmisten** [comment]
By logs I mean whatever text shows up in your terminal after running `node NeweggBot.js`,

for example:
```
$ node NeweggBot.js 
Thu Dec 31 2020 19:30:45 : Started
Thu Dec 31 2020 19:30:56 : Manual authorization code required by Newegg.  This should only happen once.
Thu Dec 31 2020 19:32:04 : Logged in
Thu Dec 31 2020 19:32:04 : Checking for card
Thu Dec 31 2020 19:32:07 : Card added to cart, attempting to purchase
Thu Dec 31 2020 19:32:07 : Starting Secure Checkout
Thu Dec 31 2020 19:32:14 : Completed purchase
```

**Comment by quantumvenom** [comment]
This is with VPN off with a combo in the config file, it finds the item and the cart loops forever following this, not adding anything else to the cart.
[2021-01-05T22:40:58.299] [INFO] Newegg Shopping Bot - Newegg Shopping Bot Started
[2021-01-05T22:41:14.175] [WARN] Newegg Shopping Bot - Manual authorization code required by Newegg.  This should only happen once.
[2021-01-05T22:41:18.761] [TRACE] Newegg Shopping Bot - Logged in
[2021-01-05T22:41:18.762] [INFO] Newegg Shopping Bot - Checking for Item

**Comment by batrarobin** [comment]
@quantumvenom The cart looping is the normal behaviour I would think, until it finds the stock. Not sure what hasn't been working for you.

@wcedmisten Thanks mate for the updated code, it's been working great since then. It's much appreciated.  Just another request if you are able to incorporate:
I find that while the bot is looping the cart searching for the stock, the login session expires in the background, after about an hour or so.  I found this when I opened another tab and tried to check my Newegg account settings or Order history etc it asked for my login details.  The workaround that I have been using is that I end up logging in manually after every hour in the second tab.  Is it possible to include in your code that while it is looping the cart, it opens a second tab in the background and inputs login details so it remains logged in.

**Comment by quantumvenom** [comment]
It loops with a combo that is in stock, I made sure to test it haha. Looping issue only ocurs when a VPN is active or the item # is a combo.

**Comment by wcedmisten** [comment]
@quantumvenom I just looked into the combo issue. For some reason, certain combos don't get added to cart, even when the website says they're in stock (tested on random flash drive combos). Maybe newegg is reporting these as in stock, even when they're out? I did succeed in using the bot on a combo that worked for manual checkout, so I don't think this is a problem with the bot, but rather with NewEgg's website.

**Comment by quantumvenom** [comment]
Shoot, how upsetting looks like snagging a 3080 won't be happening anytime soon haha. Thanks for the reply, I have a few things I can try, before I give up on it for now, I'll update with my results.

**Comment by quantumvenom** [comment]
You were right for sure, no changes made and bot was working today, only it couldn't find the cart :( And all my info is setup properly, double checked just now
The next attempt will be performed in 10739 ms
[2021-01-10T19:11:58.398] [INFO] Newegg Shopping Bot - Item added to cart, attempting to purchase
[2021-01-10T19:11:58.399] [INFO] Newegg Shopping Bot - Starting Secure Checkout
[2021-01-10T19:12:06.408] [ERROR] Newegg Shopping Bot - Cannot find the Place Order button.
[2021-01-10T19:12:06.408] [WARN] Newegg Shopping Bot - Please make sure that your Newegg account defaults for: shipping address, billing address, and payment method have been set.

**Comment by northmatt** [comment]
> It loops with a combo that is in stock, I made sure to test it haha. Looping issue only occurs when a VPN is active or the item # is a combo. Can't seem to find the cause myself, although not too experienced with js admittedly.

PR [43](https://github.com/Ataraksia/NeweggBot/pull/43) should fix this issue as it has been moved it over to a wishlist based system. So, add the combo to the wishlist and it should work. Also, I didn't have any looping issues when I was using a VPN with this PR. Don't know why wcedmisten's has some issues, my guess would be to timeout issues from waiting defined amounts of time if it is similar to the base code.

**Pull request closed without merging**
